version: "3.3"

services:
  cdn_service:
    image: cdn_image
    volumes:
      - cdn_main:/app/data/cdn_main
      - cdn_1:/app/data/cdn_1
      - cdn_2:/app/data/cdn_2
    ports:
      - "8080:8080"

  nginx_cdn_main:
    image: nginx:1.19.2
    container_name: nginx_cdn_main
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_main:/cdn/
    ports:
      - "8081:80"
    depends_on:
      - cdn_service
    env_file:
      - nginx/.env.example

  nginx_cdn_1:
    image: nginx:1.19.2
    container_name: nginx_cdn_1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_1:/cdn/
    ports:
      - "8082:80"
    depends_on:
      - cdn_service
    env_file:
      - nginx/.env.example

  nginx_cdn_2:
    image: nginx:1.19.2
    container_name: nginx_cdn_2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_2:/cdn/
    ports:
      - "80831:80"
    depends_on:
      - cdn_service
    env_file:
      - nginx/.env.example


volumes:
  cdn_main:
    external: true
  cdn_1:
    external: true
  cdn_2:
    external: true
