version: "3.3"

services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    logging:
      driver: none
    ports:
      - "6379:6379"

  nginx_cdn_main:
    image: nginx:1.19.2
    container_name: nginx_cdn_main
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_main:/cdn/
    ports:
      - "8081:80"
    env_file:
      - nginx/.env.example

  nginx_cdn_1:
    image: nginx:1.19.2
    container_name: nginx_cdn_1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_1:/cdn/
    ports:
      - "8082:80"
    env_file:
      - nginx/.env.example

  nginx_cdn_2:
    image: nginx:1.19.2
    container_name: nginx_cdn_2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_2:/cdn/
    ports:
      - "8083:80"
    env_file:
      - nginx/.env.example


volumes:
  cdn_main:
    external: true
  cdn_1:
    external: true
  cdn_2:
    external: true
