FROM python:3.9.12-alpine

EXPOSE 8080/tcp

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY requirements.dev.txt /app/requirements.dev.txt

RUN apk update --no-cache \
&& apk add build-base --no-cache --virtual .build-deps \
&& pip install setuptools --upgrade \
&& pip install --no-cache-dir -r requirements.dev.txt \
&& apk del .build-deps

COPY src/service/ /app/service/
COPY src/functional/ /app/functional/

ENTRYPOINT ["pytest", "-s", "-v", "--asyncio-mode=strict", "functional/"]
