version: "3.3"

services:
  cdn_service:
    image: cdn_image
    volumes:
      - cdn_main:/app/data/cdn_main
      - cdn_1:/app/data/cdn_1
      - cdn_2:/app/data/cdn_2
    ports:
      - "8080:8080"

volumes:
  cdn_main:
    external: true
  cdn_1:
    external: true
  cdn_2:
    external: true
