FROM python:3.9.12-alpine

EXPOSE 8080/tcp

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY requirements.dev.txt /app/requirements.dev.txt
COPY src/wait_for_pg.py /app/wait_for_pg.py
COPY src/wait_for_redis.py /app/wait_for_redis.py

RUN apk update --no-cache \
&& apk add build-base --no-cache --virtual .build-deps \
&& pip install setuptools --upgrade \
&& pip install --no-cache-dir -r requirements.dev.txt \
&& apk del .build-deps

COPY src/service/ /app/service/
COPY src/functional/ /app/functional/

ENTRYPOINT python3 wait_for_pg.py; python3 wait_for_redis.py; pytest -o log_cli=true -s -v --asyncio-mode=strict --log-cli-level=INFO functional/
