version: "3.5"

services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    logging:
      driver: none
    ports:
      - "6379:6379"

  cdn_service:
    image: cdn_image
    volumes:
      - cdn_main:/app/data/cdn_main
      - cdn_1:/app/data/cdn_1
      - cdn_2:/app/data/cdn_2
    environment:
      - CDN_DB_HOST=db
      - CDN_DB_RECREATE=true
      - CDN_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  nginx_cdn_main:
    image: nginx:1.19.2
    container_name: nginx_cdn_main
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_main:/cdn/
    ports:
      - "8081:80"
    env_file:
      - nginx/.env.example
    depends_on:
      - cdn_service


  nginx_cdn_1:
    image: nginx:1.19.2
    container_name: nginx_cdn_1
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_1:/cdn/
    ports:
      - "8082:80"
    env_file:
      - nginx/.env.example
    depends_on:
      - cdn_service

  nginx_cdn_2:
    image: nginx:1.19.2
    container_name: nginx_cdn_2
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
      - cdn_2:/cdn/
    ports:
      - "8083:80"
    env_file:
      - nginx/.env.example
    depends_on:
      - cdn_service


volumes:
  cdn_main:
    name: cdn_main_volume
  cdn_1:
    external: true
  cdn_2:
    external: true
